---
- name: Check for existing EPEL repo
  stat: path=/etc/yum.repos.d/epel.repo
  register: repofile

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: repofile is not defined

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: repofile is not defined
